//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosk.KiosksServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KiosksConfiguration", Namespace="http://schemas.datacontract.org/2004/07/CriterionManufacturingSolutions.Products." +
        "KiosksSolution")]
    [System.SerializableAttribute()]
    public partial class KiosksConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KiosksMACIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BayID {
            get {
                return this.BayIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BayIDField, value) != true)) {
                    this.BayIDField = value;
                    this.RaisePropertyChanged("BayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionName {
            get {
                return this.FunctionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionNameField, value) != true)) {
                    this.FunctionNameField = value;
                    this.RaisePropertyChanged("FunctionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KiosksMACId {
            get {
                return this.KiosksMACIdField;
            }
            set {
                if ((object.ReferenceEquals(this.KiosksMACIdField, value) != true)) {
                    this.KiosksMACIdField = value;
                    this.RaisePropertyChanged("KiosksMACId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonthlyRate", Namespace="http://schemas.datacontract.org/2004/07/CriterionManufacturingSolutions.Products." +
        "KiosksSolution")]
    [System.SerializableAttribute()]
    public partial class MonthlyRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardDetails", Namespace="http://schemas.datacontract.org/2004/07/CriterionManufacturingSolutions.Products." +
        "KiosksSolution")]
    [System.SerializableAttribute()]
    public partial class CreditCardDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidTillDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidTillDate {
            get {
                return this.ValidTillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidTillDateField, value) != true)) {
                    this.ValidTillDateField = value;
                    this.RaisePropertyChanged("ValidTillDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KiosksServices.ICCManagerService", CallbackContract=typeof(Kiosk.KiosksServices.ICCManagerServiceCallback))]
    public interface ICCManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/GetConfiguration", ReplyAction="http://tempuri.org/ICCManagerService/GetConfigurationResponse")]
        Kiosk.KiosksServices.KiosksConfiguration GetConfiguration(string kiosksMacID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/GetMonthlyRates", ReplyAction="http://tempuri.org/ICCManagerService/GetMonthlyRatesResponse")]
        Kiosk.KiosksServices.MonthlyRate[] GetMonthlyRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/IsBayReadyForStore", ReplyAction="http://tempuri.org/ICCManagerService/IsBayReadyForStoreResponse")]
        bool IsBayReadyForStore(string BayID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/IsBayReadyForRetrieval", ReplyAction="http://tempuri.org/ICCManagerService/IsBayReadyForRetrievalResponse")]
        bool IsBayReadyForRetrieval(string BayID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/IsValidCreditCard", ReplyAction="http://tempuri.org/ICCManagerService/IsValidCreditCardResponse")]
        bool IsValidCreditCard(Kiosk.KiosksServices.CreditCardDetails creditCard);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCManagerServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/IsBayReadyForStoreCallback", ReplyAction="http://tempuri.org/ICCManagerService/IsBayReadyForStoreCallbackResponse")]
        bool IsBayReadyForStoreCallback(bool bayStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCManagerService/IsBayReadyForRetrievalCallback", ReplyAction="http://tempuri.org/ICCManagerService/IsBayReadyForRetrievalCallbackResponse")]
        bool IsBayReadyForRetrievalCallback(bool bayStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCManagerServiceChannel : Kiosk.KiosksServices.ICCManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCManagerServiceClient : System.ServiceModel.DuplexClientBase<Kiosk.KiosksServices.ICCManagerService>, Kiosk.KiosksServices.ICCManagerService {
        
        public CCManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CCManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CCManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CCManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CCManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Kiosk.KiosksServices.KiosksConfiguration GetConfiguration(string kiosksMacID) {
            return base.Channel.GetConfiguration(kiosksMacID);
        }
        
        public Kiosk.KiosksServices.MonthlyRate[] GetMonthlyRates() {
            return base.Channel.GetMonthlyRates();
        }
        
        public bool IsBayReadyForStore(string BayID) {
            return base.Channel.IsBayReadyForStore(BayID);
        }
        
        public bool IsBayReadyForRetrieval(string BayID) {
            return base.Channel.IsBayReadyForRetrieval(BayID);
        }
        
        public bool IsValidCreditCard(Kiosk.KiosksServices.CreditCardDetails creditCard) {
            return base.Channel.IsValidCreditCard(creditCard);
        }
    }
}
